### ISSUE TITLE
deg to rad

### ISSUE THREAD

**Issue by xmfcx** [meliketanrikulu/ROS2-Simple-Navigation#1]
https://github.com/meliketanrikulu/ROS2-Simple-Navigation/blob/448d6ad8128a19cdd6e9dc2679d2126d17d316e5/navigation/src/Publisher.cpp#L31-L32

Buralarda `cos(static_cast<float>(i) * M_PI / 180.0f))` şeklinde radyan cinsinden verirsen https://docs.google.com/spreadsheets/d/10vxkBKwmC82VESPM83hr2FbqmnAwGPXvGHFd-O2IcTE/edit?usp=sharing buradaki gibi bir şekil elde edebilirsin.

**Comment by meliketanrikulu** [comment]
Çok teşekkürler güncelledim sonuçları.  @xmfcx
